//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDataRatingsAndReviewsManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackDB
    {
        public int RatingID { get; set; }
        public int TransactionID { get; set; }
        public int UserID { get; set; }
        public string Username { get; set; }
        public int RateNumber { get; set; }
        public string Feedbacks { get; set; }
        public string DateInserted { get; set; }
    }
}
