//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDataRatingsAndReviewsManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomDB
    {
        public int RoomID { get; set; }
        public string RoomImage { get; set; }
        public string RoomType { get; set; }
        public decimal RoomPrice { get; set; }
    }
}
