//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDataRatingsAndReviewsManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDB
    {
        public int TransactionID { get; set; }
        public int UserID { get; set; }
        public string Username { get; set; }
        public string LastUpdateTime { get; set; }
        public string LastUpdateDate { get; set; }
        public string RoomImage { get; set; }
        public string RoomType { get; set; }
        public string ArrivalDate { get; set; }
        public string ArrivalTime { get; set; }
        public string DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public int NumberOfNight { get; set; }
        public int NumberOfOccupants { get; set; }
        public string RoomMasterID { get; set; }
        public decimal RoomPrice { get; set; }
        public string Status { get; set; }
        public string IsRated { get; set; }
    }
}
