//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDataRatingsAndReviewsManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccTBL
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string AccountPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string HomeAddress { get; set; }
        public int Age { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public int ZIPcode { get; set; }
        public string SimNumber { get; set; }
        public string Roles { get; set; }
        public string ImagePath { get; set; }
    }
}
