//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDataRatingsAndReviewsManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImgTBL
    {
        public System.Guid ImageID { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public string ImagePath { get; set; }
    }
}
